// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ManageCourses.Models
{
    [Table("Admin")]
    public partial class Admin
    {
        [Key]
        public int id { get; set; }
        [StringLength(100)]
        public string name { get; set; }
        [StringLength(199)]
        public string email { get; set; }
        [StringLength(30)]
        public string password { get; set; }
    }
}