// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ManageCourses.Models
{
    [Table("category")]
    public partial class category
    {
        public category()
        {
            Courses = new HashSet<Course>();
            Inverseparent = new HashSet<category>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(100)]
        public string name { get; set; }
        public int? parentId { get; set; }

        [ForeignKey("parentId")]
        [InverseProperty("Inverseparent")]
        public virtual category parent { get; set; }
        [InverseProperty("category")]
        public virtual ICollection<Course> Courses { get; set; }
        [InverseProperty("parent")]
        public virtual ICollection<category> Inverseparent { get; set; }
    }
}