// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ManageCourses.Models
{
    [Table("Course")]
    public partial class Course
    {
        public Course()
        {
            Course_Lessons = new HashSet<Course_Lesson>();
            trainee_courses = new HashSet<trainee_course>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(100)]
        public string name { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public string description { get; set; }
        public int? trainerId { get; set; }
        public int? categoryId { get; set; }

        [ForeignKey("categoryId")]
        [InverseProperty("Courses")]
        public virtual category category { get; set; }
        [ForeignKey("trainerId")]
        [InverseProperty("Courses")]
        public virtual trainer trainer { get; set; }
        [InverseProperty("course")]
        public virtual ICollection<Course_Lesson> Course_Lessons { get; set; }
        [InverseProperty("course")]
        public virtual ICollection<trainee_course> trainee_courses { get; set; }
    }
}