// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ManageCourses.Models
{
    public partial class Course_Lesson
    {
        [Key]
        public int id { get; set; }
        [StringLength(200)]
        public string title { get; set; }
        public int? course_id { get; set; }
        public int? order_number { get; set; }

        [ForeignKey("course_id")]
        [InverseProperty("Course_Lessons")]
        public virtual Course course { get; set; }
    }
}