// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ManageCourses.Models
{
    [Table("trainer")]
    public partial class trainer
    {
        public trainer()
        {
            Courses = new HashSet<Course>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(100)]
        public string name { get; set; }
        [StringLength(100)]
        public string email { get; set; }
        public string description { get; set; }
        [StringLength(250)]
        public string website { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime creationDate { get; set; }

        [InverseProperty("trainer")]
        public virtual ICollection<Course> Courses { get; set; }
    }
}