// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ManageCourses.Models
{
    [Table("trainee")]
    public partial class trainee
    {
        public trainee()
        {
            trainee_courses = new HashSet<trainee_course>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(100)]
        public string name { get; set; }
        [StringLength(100)]
        public string email { get; set; }
        [StringLength(30)]
        public string password { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? creationDate { get; set; }
        public bool? isActive { get; set; }

        [InverseProperty("trainee")]
        public virtual ICollection<trainee_course> trainee_courses { get; set; }
    }
}