// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ManageCourses.Models
{
    [Table("trainee_course")]
    public partial class trainee_course
    {
        [Key]
        public int trainee_id { get; set; }
        [Key]
        public int course_id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? registration_date { get; set; }

        [ForeignKey("course_id")]
        [InverseProperty("trainee_courses")]
        public virtual Course course { get; set; }
        [ForeignKey("trainee_id")]
        [InverseProperty("trainee_courses")]
        public virtual trainee trainee { get; set; }
    }
}